version: '3'

services:
  idhagnbot:
    image: ghcr.io/akuma-real/idhagnbot-docker:latest
    volumes:
      - ./configs:/app/configs
      - ./resources:/app/resources
      - ./states:/app/states
    restart: unless-stopped
    ports:
      - "8080:8080" 